#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the QTC network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x9d,0xe6,0xc2,0x92,0x4d,0x2b,
    0x01,0x04,0xa7,0x63,0xb5,0x83,0x4d,0x2b,
};

// chainparams_seed_signet: no entries

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x9d,0xe6,0xc2,0x92,0x74,0x3b,
    0x01,0x04,0xa7,0x63,0xb5,0x83,0x74,0x3b,
};

// chainparams_seed_testnet4: no entries
#endif // BITCOIN_CHAINPARAMSSEEDS_H
