FROM alpine:3.22 AS builder
RUN apk add --no-cache build-base cmake boost-dev libevent-dev sqlite-dev zeromq-dev coreutils binutils python3
WORKDIR /opt/qtc
COPY . .
WORKDIR /opt/qtc/build
RUN cmake .. \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DBUILD_DAEMON="ON" -DBUILD_CLI="ON" -DENABLE_WALLET="ON" -DWITH_SQLITE="ON" \
    -DBUILD_TESTS="ON" -DBUILD_GUI="OFF" -DBUILD_TX="OFF" -DBUILD_UTIL="OFF" \
    -DBUILD_WALLET_TOOL="OFF" -DBUILD_BENCH="OFF" -DBUILD_FUZZ_BINARY="OFF" \
    -DBUILD_UTIL_CHAINSTATE="OFF" -DWITH_BDB="OFF" -DWITH_USDT="OFF" \
    -DINSTALL_MAN="OFF" -DWITH_CCACHE="OFF" -DWITH_ZMQ="OFF"
RUN cmake --build . --target test_qtc -j$(nproc)
