#!/usr/bin/env bash
#
#  qtcd The QTC server.
#
#
# chkconfig: 345 80 20
# description: qtcd
# processname: qtcd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/qtcd, see below
if [ -f /etc/sysconfig/qtcd ]; then
        . /etc/sysconfig/qtcd
fi

RETVAL=0

prog=qtcd
# you can override the lockfile via QTCD_LOCKFILE in /etc/sysconfig/qtcd
lockfile=${QTCD_LOCKFILE-/var/lock/subsys/qtcd}

# qtcd defaults to /usr/bin/qtcd, override with QTCD_BIN
qtcd=${QTCD_BIN-/usr/bin/qtcd}

# qtcd opts default to -disablewallet, override with QTCD_OPTS
qtcd_opts=${QTCD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $qtcd $qtcd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
